version: '3'
services:

  tebo-sample-db:
    image: mariadb:10.7
    container_name: tebo-sample-db
    working_dir: /application
    #removed NO_ZERO_IN_DATE,NO_ZERO_DATE from SQL_MODE to allow bookings.confirmed and other columns work with zeroes in dates
    #command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;' --sql-mode="NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_USER=my_app
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./:/application
      - ./tmp/data/tebo-sample_db:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - '3809:3306'

  tebo-sample:
    #image: arodu/cakephp:nginx-php80
    image: arodu/cakephp:nginx-php80-alpine
    container_name: tebo-sample
    working_dir: /application
    volumes:
      - ./:/application
      - ~/.ssh:/home/application/.ssh:ro
    environment:
      - WEB_DOCUMENT_ROOT=/application/webroot
      - DATABASE_URL=mysql://root:password@tebo-sample-db:3306/tebo-sample
      - DATABASE_TEST_URL=mysql://root:password@tebo-sample-db:3306/tebo-sample_test
    ports:
      - "8809:80"
